INSERT INTO roles (name) SELECT 'ROLE_LOREN' WHERE NOT EXISTS (SELECT * FROM roles WHERE name = 'ROLE_LOREN');
INSERT INTO roles (name) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT * FROM roles WHERE name = 'ROLE_ADMIN');
INSERT INTO roles (name) SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT * FROM roles WHERE name = 'ROLE_USER');